/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller_DAO.AgendamentosDao;
import Controller_DAO.DoadoresDao;
import Model.Agendamentos;
import Model.Doadores;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.sql.Date;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gianderson.girardi
 */
public class AgendamentoView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AgendamentoView() {
        initComponents();
        carregaDados();
        this.setLocationRelativeTo(null);
        
        DoadoresDao Dao = new DoadoresDao();

        for (Doadores d : Dao.listar()) {
            SelecionarDoador.addItem(d);
            
        }
    }

    public void carregaDados() {

        DefaultTableModel tabela = (DefaultTableModel) jTableAgendamentos.getModel();
        AgendamentosDao dao = new AgendamentosDao();
        tabela.setNumRows(0);

        for (Agendamentos A : dao.listar()) {
            tabela.addRow(new Object[]{
                A.getId_agendamento(),
                A.getData(),
                A.getHora(),
                A.getDoador()
            });
        }
    }
    public void pesquisaDados(){
        
        DefaultTableModel tabela = (DefaultTableModel) jTableAgendamentos.getModel();      
        AgendamentosDao dao = new AgendamentosDao();
        tabela.setNumRows(0);
                
        for (Agendamentos A : dao.listarDia(CampoPesquisa.getText())){
            tabela.addRow(new Object[]{
                A.getId_agendamento(),
                A.getData(),
                A.getHora(),
                A.getDoador()
            });
        }        
    }
    
     public void LimparCampos() {
        CampoId.setText("");
        CampoData.setText("");
        CampoHora.setText("");
        CampoPesquisa.setText("");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampoId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoHora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotãoCadastrar = new javax.swing.JButton();
        BotãoAlterar = new javax.swing.JButton();
        BotãoExcluir = new javax.swing.JButton();
        BotãoPesquisar = new javax.swing.JButton();
        CampoPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgendamentos = new javax.swing.JTable();
        BotãoLimpar = new javax.swing.JButton();
        SelecionarDoador = new javax.swing.JComboBox<>();
        BotãoFechar = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Codigo:");

        CampoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Data:");

        CampoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDataActionPerformed(evt);
            }
        });

        jLabel3.setText("Hora:");

        jLabel4.setText("Doador:");

        BotãoCadastrar.setText("Cadastrar");
        BotãoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoCadastrarActionPerformed(evt);
            }
        });

        BotãoAlterar.setText("Alterar");
        BotãoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoAlterarActionPerformed(evt);
            }
        });

        BotãoExcluir.setText("Excluir");
        BotãoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoExcluirActionPerformed(evt);
            }
        });

        BotãoPesquisar.setText("Pesquisar");
        BotãoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoPesquisarActionPerformed(evt);
            }
        });

        CampoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaActionPerformed(evt);
            }
        });

        jTableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Hora", "Data", "Doador"
            }
        ));
        jTableAgendamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAgendamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAgendamentos);

        BotãoLimpar.setText("Limpar");
        BotãoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoLimparActionPerformed(evt);
            }
        });

        BotãoFechar.setText("Fechar");
        BotãoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelecionarDoador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CampoPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotãoPesquisar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoData))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoHora))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotãoCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(BotãoAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(BotãoExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(BotãoLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(BotãoFechar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SelecionarDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotãoCadastrar)
                    .addComponent(BotãoAlterar)
                    .addComponent(BotãoExcluir)
                    .addComponent(BotãoLimpar)
                    .addComponent(BotãoFechar))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotãoPesquisar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIdActionPerformed

    private void CampoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDataActionPerformed

    private void CampoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisaActionPerformed

    private void BotãoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoExcluirActionPerformed
        Agendamentos agend = new Agendamentos();
        AgendamentosDao DAO = new AgendamentosDao();

        agend.setId_agendamento(Integer.parseInt(CampoId.getText()));
        
        DAO.excluir(agend);
        carregaDados();
    }//GEN-LAST:event_BotãoExcluirActionPerformed

    private void BotãoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoCadastrarActionPerformed
        try {
            Agendamentos a = new Agendamentos();
            AgendamentosDao DAO = new AgendamentosDao();

            a.setId_agendamento(Integer.parseInt(CampoId.getText()));

            SimpleDateFormat dataString = new SimpleDateFormat("yyyy-MM-dd");
            Date date = (Date) dataString.parse(CampoData.getText());
            a.setData(date);

            SimpleDateFormat dString = new SimpleDateFormat("hh.mm.ss");
            Time time = (Time) dString.parse(CampoHora.getText());
            a.setHora(time);

            Doadores doador = (Doadores) SelecionarDoador.getSelectedItem();
            a.setDoador(doador);

            DAO.cadastrar(a);

        } catch (ParseException ex) {
            Logger.getLogger(AgendamentoView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BotãoCadastrarActionPerformed

    private void BotãoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotãoAlterarActionPerformed

    private void BotãoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_BotãoLimparActionPerformed

    private void BotãoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoFecharActionPerformed
        AgendamentoView.this.dispose();
    }//GEN-LAST:event_BotãoFecharActionPerformed

    private void BotãoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoPesquisarActionPerformed
        pesquisaDados();
    }//GEN-LAST:event_BotãoPesquisarActionPerformed

    private void jTableAgendamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAgendamentosMouseClicked
        CampoId.setText(jTableAgendamentos.getValueAt(jTableAgendamentos.getSelectedRow(), 0).toString());
        CampoData.setText(jTableAgendamentos.getValueAt(jTableAgendamentos.getSelectedRow(), 1).toString());
        CampoHora.setText(jTableAgendamentos.getValueAt(jTableAgendamentos.getSelectedRow(), 2).toString());
        
        String Edit = jTableAgendamentos.getValueAt(jTableAgendamentos.getSelectedRow(), 3).toString();
        for(int i = 0; i < SelecionarDoador.getItemCount();i++){
            if(SelecionarDoador.getItemAt(i).toString().equalsIgnoreCase(Edit)){
                SelecionarDoador.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_jTableAgendamentosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendamentoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoAlterar;
    private javax.swing.JButton BotãoCadastrar;
    private javax.swing.JButton BotãoExcluir;
    private javax.swing.JButton BotãoFechar;
    private javax.swing.JButton BotãoLimpar;
    private javax.swing.JButton BotãoPesquisar;
    private javax.swing.JTextField CampoData;
    private javax.swing.JTextField CampoHora;
    private javax.swing.JTextField CampoId;
    private javax.swing.JTextField CampoPesquisa;
    private javax.swing.JComboBox<Object> SelecionarDoador;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAgendamentos;
    // End of variables declaration//GEN-END:variables
}
