/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author diegomenegazzi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        IMN_Agendamentos = new javax.swing.JMenu();
        MI_Agendamentos = new javax.swing.JMenuItem();
        MI_Cidades = new javax.swing.JMenuItem();
        MI_Colaboradores = new javax.swing.JMenuItem();
        MI_Doadores = new javax.swing.JMenuItem();
        MI_Entidades = new javax.swing.JMenuItem();
        MI_Saída_sangue = new javax.swing.JMenuItem();
        MI_Tipo_sanguineo = new javax.swing.JMenuItem();
        MI_Usuários = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agendamentos do dia"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IMN_Agendamentos.setText("Cadastros");

        MI_Agendamentos.setText("Agendamentos");
        MI_Agendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_AgendamentosActionPerformed(evt);
            }
        });
        IMN_Agendamentos.add(MI_Agendamentos);

        MI_Cidades.setText("Cidades");
        MI_Cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_CidadesActionPerformed(evt);
            }
        });
        IMN_Agendamentos.add(MI_Cidades);

        MI_Colaboradores.setText("Colaboradores");
        MI_Colaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ColaboradoresActionPerformed(evt);
            }
        });
        IMN_Agendamentos.add(MI_Colaboradores);

        MI_Doadores.setText("Doadores");
        MI_Doadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_DoadoresActionPerformed(evt);
            }
        });
        IMN_Agendamentos.add(MI_Doadores);

        MI_Entidades.setText("Entidades");
        MI_Entidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_EntidadesActionPerformed(evt);
            }
        });
        IMN_Agendamentos.add(MI_Entidades);

        MI_Saída_sangue.setText("Saída de estoque");
        MI_Saída_sangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_Saída_sangueActionPerformed(evt);
            }
        });
        IMN_Agendamentos.add(MI_Saída_sangue);

        MI_Tipo_sanguineo.setText("Tipo Sanguíneo");
        MI_Tipo_sanguineo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_Tipo_sanguineoActionPerformed(evt);
            }
        });
        IMN_Agendamentos.add(MI_Tipo_sanguineo);

        MI_Usuários.setText("Usuários");
        MI_Usuários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_UsuáriosActionPerformed(evt);
            }
        });
        IMN_Agendamentos.add(MI_Usuários);

        jMenuBar1.add(IMN_Agendamentos);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MI_UsuáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_UsuáriosActionPerformed
        UsuariosView usuarios = new UsuariosView();
        usuarios.setVisible(true);
    }//GEN-LAST:event_MI_UsuáriosActionPerformed

    private void MI_ColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ColaboradoresActionPerformed
        ColaboradoresView c = new ColaboradoresView();
        c.setVisible(true);
    }//GEN-LAST:event_MI_ColaboradoresActionPerformed

    private void MI_DoadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_DoadoresActionPerformed
        DoadoresView c = new DoadoresView();
        c.setVisible(true);
    }//GEN-LAST:event_MI_DoadoresActionPerformed

    private void MI_Tipo_sanguineoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_Tipo_sanguineoActionPerformed
        TipoSanguineoView ts = new TipoSanguineoView();
        ts.setVisible(true);
    }//GEN-LAST:event_MI_Tipo_sanguineoActionPerformed

    private void MI_AgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_AgendamentosActionPerformed
        AgendamentoView ag = new AgendamentoView();
        ag.setVisible(true);
    }//GEN-LAST:event_MI_AgendamentosActionPerformed

    private void MI_CidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_CidadesActionPerformed
        CidadesView cid = new CidadesView();
        cid.setVisible(true);
    }//GEN-LAST:event_MI_CidadesActionPerformed

    private void MI_EntidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_EntidadesActionPerformed
        EntidadesView enti = new EntidadesView();
        enti.setVisible(true);
    }//GEN-LAST:event_MI_EntidadesActionPerformed

    private void MI_Saída_sangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_Saída_sangueActionPerformed
        SaidaSangueView saida = new SaidaSangueView();
        saida.setVisible(true);
    }//GEN-LAST:event_MI_Saída_sangueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu IMN_Agendamentos;
    private javax.swing.JMenuItem MI_Agendamentos;
    private javax.swing.JMenuItem MI_Cidades;
    private javax.swing.JMenuItem MI_Colaboradores;
    private javax.swing.JMenuItem MI_Doadores;
    private javax.swing.JMenuItem MI_Entidades;
    private javax.swing.JMenuItem MI_Saída_sangue;
    private javax.swing.JMenuItem MI_Tipo_sanguineo;
    private javax.swing.JMenuItem MI_Usuários;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
