-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 11:35:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_hemosc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_hemosc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_hemosc` DEFAULT CHARACTER SET utf8 ;
USE `db_hemosc` ;

-- -----------------------------------------------------
-- Table `db_hemosc`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hemosc`.`cidades` (
  `id_cidade` INT NOT NULL auto_increment,
  `codigo_ibge` INT NULL,
  `descricao` VARCHAR(100) NULL,
  `uf` CHAR(2) NULL,
  PRIMARY KEY (`id_cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hemosc`.`tipos_sanguineos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hemosc`.`tipos_sanguineos` (
  `id_tipo_sanguineo` INT NOT NULL auto_increment,
  `descricao` VARCHAR(45) NULL,
  `fator_rh` VARCHAR(45) NULL,
  `estoque` INT NULL,
  `estoque_minimo` INT NULL,
  PRIMARY KEY (`id_tipo_sanguineo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hemosc`.`doadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hemosc`.`doadores` (
  `id_doador` INT NOT NULL auto_increment,
  `id_cidade` INT NOT NULL,
  `id_tipo_sanguineo` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NULL,
  `data_nascimento` DATE NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  PRIMARY KEY (`id_doador`),
  INDEX `fk_doadores_cidades_idx` (`id_cidade` ASC) VISIBLE,
  INDEX `fk_doadores_tipos_sanguineos1_idx` (`id_tipo_sanguineo` ASC) VISIBLE,
  CONSTRAINT `fk_doadores_cidades`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `db_hemosc`.`cidades` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doadores_tipos_sanguineos1`
    FOREIGN KEY (`id_tipo_sanguineo`)
    REFERENCES `db_hemosc`.`tipos_sanguineos` (`id_tipo_sanguineo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hemosc`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hemosc`.`colaboradores` (
  `id_colaborador` INT NOT NULL auto_increment,
  `id_cidade` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NULL,
  `funcao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_colaborador`),
  INDEX `fk_colaboradores_cidades1_idx` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_colaboradores_cidades1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `db_hemosc`.`cidades` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hemosc`.`doacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hemosc`.`doacoes` (
  `id_doacao` INT NOT NULL auto_increment,
  `data` DATE NULL,
  `id_doador` INT NOT NULL,
  `id_tipo_sanguineo` INT NOT NULL,
  `id_colaborador` INT NOT NULL,
  PRIMARY KEY (`id_doacao`),
  INDEX `fk_doacoes_doadores1_idx` (`id_doador` ASC) VISIBLE,
  INDEX `fk_doacoes_tipos_sanguineos1_idx` (`id_tipo_sanguineo` ASC) VISIBLE,
  INDEX `fk_doacoes_colaboradores1_idx` (`id_colaborador` ASC) VISIBLE,
  CONSTRAINT `fk_doacoes_doadores1`
    FOREIGN KEY (`id_doador`)
    REFERENCES `db_hemosc`.`doadores` (`id_doador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacoes_tipos_sanguineos1`
    FOREIGN KEY (`id_tipo_sanguineo`)
    REFERENCES `db_hemosc`.`tipos_sanguineos` (`id_tipo_sanguineo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacoes_colaboradores1`
    FOREIGN KEY (`id_colaborador`)
    REFERENCES `db_hemosc`.`colaboradores` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hemosc`.`entidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hemosc`.`entidades` (
  `id_entidade` INT NOT NULL auto_increment,
  `id_cidade` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`id_entidade`),
  INDEX `fk_entidades_cidades1_idx` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_entidades_cidades1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `db_hemosc`.`cidades` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hemosc`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hemosc`.`agendamento` (
  `id_agendamento` INT NOT NULL auto_increment,
  `data` DATE NULL,
  `hora` TIME NULL,
  `id_doador` INT NOT NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `fk_agendamento_doadores1_idx` (`id_doador` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_doadores1`
    FOREIGN KEY (`id_doador`)
    REFERENCES `db_hemosc`.`doadores` (`id_doador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_hemosc`.`saida_sangue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hemosc`.`saida_sangue` (
  `id_saida_sangue` INT NOT NULL auto_increment,
  `id_entidade` INT NOT NULL,
  `id_tipo_sanguineo` INT NOT NULL,
  `data` DATETIME NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_saida_sangue`),
  INDEX `fk_saida_sangue_tipos_sanguineos1_idx` (`id_tipo_sanguineo` ASC) VISIBLE,
  INDEX `fk_saida_sangue_entidades1_idx` (`id_entidade` ASC) VISIBLE,
  CONSTRAINT `fk_saida_sangue_tipos_sanguineos1`
    FOREIGN KEY (`id_tipo_sanguineo`)
    REFERENCES `db_hemosc`.`tipos_sanguineos` (`id_tipo_sanguineo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saida_sangue_entidades1`
    FOREIGN KEY (`id_entidade`)
    REFERENCES `db_hemosc`.`entidades` (`id_entidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

create table usuarios(
codigo int not null auto_increment,
nome varchar(100),
email varchar(100),
senha varchar(45),
primary key(codigo));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
